# -*- coding: utf-8 -*-
"""Hackathon_Auto_ViML.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tvoJtlcOrQA1q2iE7YZQfqqm2sK6XACS
"""

import pandas as pd
import numpy as np

train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
print(train.shape, test.shape)
target = 'target'
train.head()

train[target] = 1000000*(train[target]-1).values

!pip install autoviml

import seaborn as sns
sns.scatterplot('span',target,data=train)

target_by_cat = pd.DataFrame(train.groupby(train['span'])[target].mean())
target_by_cat.plot()
print(target_by_cat.shape)
target_by_cat.head()

new_col = 'target_mean_by_cat'
train[new_col] = train.groupby('span')['target'].transform('median')
train.head()

test[new_col] = test.span.map(train.groupby('span')['target'].median())
test.head()

### This is the submission data frame ####
subm = pd.DataFrame()
subm['id'] = test['id'].values
subm['target'] = 0.0
print(subm.shape)
subm.head()

from autoviml.Auto_ViML import Auto_ViML
sample_submission = subm
scoring_parameter = 'rmse'
model, feats, trainm, testm = Auto_ViML(train[sel_feats+[new_col,target]], target, test[sel_feats+[new_col]], sample_submission=subm, 
          hyper_param='GS', feature_reduction=True,
          scoring_parameter=scoring_parameter, Boosting_Flag=False, KMeans_Featurizer=True, 
          Add_Poly=0, Stacking_Flag=True, Binning_Flag=True, Imbalanced_Flag=False, verbose=0)

preds = [x for x in list(train) if x not in [target]]
test[target] = -1.0
df = train.append(test)
print(df.shape)
df.head(2)

from autoviz.AutoViz_Class  import AutoViz_Class
AV = AutoViz_Class()
dft = AV.AutoViz(filename="", sep=',', depVar='target', dfte=df)

### AutoViz has selected top 30 features => let's use them to build a model.
sel_feats = dft.columns[:30].tolist()
sel_feats



#model.predict(testm[feats])
testm.head()

